feat: controllers, models, tests
HoneyVanity/java-filmorate pull request #1
Opened 2023-01-23 23:58 UTC by HoneyVanity

2023-01-25 00:25 UTC, NikolaiDem requested changes

2023-01-25 00:25 UTC, NikolaiDem commented on pom.xml
> +	<repositories>
.для чего добавлены репозитории?

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage storage = new InMemoryFilmStorage();
private final и
Вместо создания объекта new InMemoryFilmStorage() добавить конструктор, а на конструктор навесить аннотацию Autowired. Таким образом spring сам создаст и внедрит нужные зависимости в наш контроллер. Объекты через new мы максимально не создаем, тем самым понижая связанность объектов модуле)

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserStorage storage = new InMemoryUserStorage();
private final и
Вместо создания объекта new InMemoryFilmStorage() добавить конструктор, а на конструктор навесить аннотацию Autowired. Таким образом spring сам создаст и внедрит нужные зависимости в наш контроллер. Объекты через new мы максимально не создаем, тем самым понижая связанность объектов модуле)

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends RuntimeException {
FilmAlreadyExistsException по функциональности совпадает с UserAlreadyExistsException. Лучше ограничиться общим исключением EntityAlreadyExistsException, а детали указать уже в message.
Аналогично для ".....NotFoundException"

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> getFilms();
CodeStyle : разделить методы пустыми строками.

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Добавить аннотацию Component, чтобы spring мог создать бин и внедрить его в нужные объекты.

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Добавить аннотацию Component, чтобы spring мог создать бин и внедрить его в нужные объекты.

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    Map<Integer, Film> films = new HashMap<>();
Все поля private

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    Validator validator = new Validator();
Все поля private

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    Validator validator = new Validator();
Для уменьшения связанности лучше добавить конструктор с аргументом Validator, к конструктору добавить аннотацию Autowired (хотя добавлять ее опционально). А сам класс Validator тогда обозначить @Component-ом

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    Validator validator = new Validator();
Для уменьшения связанности лучше добавить конструктор с аргументом Validator, к конструктору добавить аннотацию Autowired (хотя добавлять ее опционально). А сам класс Validator тогда обозначить @Component-ом

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +                        f.getReleaseDate() == film.getReleaseDate())) {
А даты релиза же 2х разных фильмов вполне могут совпасть?)

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +                        u.getBirthday() == user.getBirthday())) {
Даты рождения же тоже могут совпасть?) Или имелось ввиду && вместо || ?

2023-01-25 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/test/ValidationTest.java
> +public class ValidationTest {
Перенести тесты в тестовый пакет

2023-01-25 15:08 UTC, HoneyVanity commented on pom.xml
> +	<repositories>
Репозитории были добавлены автоматически при создании проекта, удалила. Хотела спросить, нормально ли это: idea предупреждает про потенциально уязвимые транзитивные зависимости в spring-boot-starter-web

2023-01-25 15:40 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage storage = new InMemoryFilmStorage();
Done

2023-01-25 15:40 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserStorage storage = new InMemoryUserStorage();
Done

2023-01-25 15:40 UTC, AleksandraArkhipova commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> getFilms();
Done

2023-01-25 15:43 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/test/ValidationTest.java
> +public class ValidationTest {
Done

2023-01-25 15:50 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    Validator validator = new Validator();
Done

2023-01-25 15:52 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +                        f.getReleaseDate() == film.getReleaseDate())) {
Думала, что достаточно будет выполнения одного условия, исправила

2023-01-25 15:52 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +                        u.getBirthday() == user.getBirthday())) {
Думала, что достаточно будет выполнения одного условия, исправила

2023-01-25 15:53 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    Validator validator = new Validator();
Done

2023-01-25 15:53 UTC, AleksandraArkhipova commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends RuntimeException {
Done

2023-01-25 16:30 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends RuntimeException {
с точки зрения связанности объектов модулей, ничего, что исключения создаются через new?

2023-01-25 17:09 UTC, HoneyVanity commented on pom.xml
> +	<repositories>
Дополнительно, хотела спросить, нормально ли это: idea предупреждает про потенциально уязвимые транзитивные зависимости в spring-boot-starter-web

2023-01-25 23:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends RuntimeException {
Да, ок

2023-01-26 00:00 UTC, NikolaiDem approved these changes

2023-01-26 00:44 UTC, merged