feat: add friends and likes
HoneyVanity/java-filmorate pull request #2
Opened 2023-02-10 21:26 UTC by HoneyVanity

2023-02-11 19:43 UTC, NikolaiDem requested changes

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@Valid @PathVariable Long id) {
Что здесь валидируется (Valid)? 
И для остальных методов ( с Long ).

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleNullPointerExc(final EntityNotFoundException e) {
Обработку исключений лучше сделать в отдельном классе ExceptionHandler.

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Обработку исключений лучше сделать в отдельном классе ExceptionHandler.

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getUser(@Valid @PathVariable Long id) {
Что здесь валидируется (Valid)?
И для остальных методов ( с Long ).

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Getter
Getter не нужен, ведь он есть в Data.

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Getter
Getter не нужен, ведь он есть в Data.

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film addLike(Long id, Long userId);
В репозитории лучше оставить методы с CRUD операциями. А методы с бизнес логикой (добавление, удаление лайка и показ популярных фильмов) лучше перенести в сервис.

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User addFriend(Long friendId, Long id);
В репозитории лучше оставить методы с CRUD операциями. А методы с бизнес логикой (добавление, удаление друга, поиск общих друзей и друзей друга) лучше перенести в сервис.

2023-02-11 19:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        System.out.println("user: " + users.get(id).getId() + ""
Лучше использовать логгер вместо System.out.println()

2023-02-13 12:03 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Getter
done

2023-02-13 12:03 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Getter
done

2023-02-13 12:03 UTC, AleksandraArkhipova commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getUser(@Valid @PathVariable Long id) {
done

2023-02-13 12:03 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@Valid @PathVariable Long id) {
done

2023-02-13 12:15 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        System.out.println("user: " + users.get(id).getId() + ""
done

2023-02-14 09:57 UTC, felixoff commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
Вместо множественных private лучше использовать @FieldDefaults

2023-02-14 13:23 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
done

2023-02-14 13:23 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User addFriend(Long friendId, Long id);
done

2023-02-14 13:23 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film addLike(Long id, Long userId);
done

2023-03-06 22:45 UTC, merged