SQL Month
HoneyVanity/java-filmorate pull request #7
Opened 2023-05-11 01:46 UTC by HoneyVanity

2023-05-11 21:04 UTC, NikolaiDem requested changes

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
Чтобы аннотации из javax.validation.constraints.* обработались, нужно к контроллеру добавить аннотацию @Validated

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +public class GenreController {
Чтобы аннотации из javax.validation.constraints.* обработались, нужно к контроллеру добавить аннотацию @validated

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +public class MpaController {
Чтобы аннотации из javax.validation.constraints.* обработались, нужно к контроллеру добавить аннотацию @validated

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@GetMapping("/{id}")
Codestyle

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
Чтобы аннотации из javax.validation.constraints.* обработались, нужно к контроллеру добавить аннотацию @validated

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    List<Genre> getByFilmId(int film_id);
Codestyle : film_id

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbDao.java
> +                .genres((genreDao.getByFilmId(resultSet.getInt("film_id"))))
Когда текущий метод (mapRowToFilm(...)) вызывается для списка фильмов, то здесь возникает проблема "N+1 query". Одним запросом получены все N фильмов, и для каждого фильма нужно сделать еще по одному запросу (на получение жанров), то есть дополнительных N запросов. Поэтому сначала можно получить список всех фильмов (List<Film> films) без жанров. А затем получить все жанры для всего списка фильмов и раскидать жанры по списку сформированных фильмов.
Или как вариант снизить количество дополнительных запросов до одного - использовать
void query(String sql, RowCallbackHandler rch, @Nullable Object... args)
Где sql - запрос на получение всех жанров (то есть такая сджойненная таблица : filmId, genreId, genreName).  Пройти по всем строкам такой сджойненной таблицы, и для каждой строки сконструировать жанр и добавить его в соответствующий фильм. Для этого установку жанров лучше вынести в отдельный метод.

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/queries/FilmQueries.java
> +            "LEFT JOIN likes AS l ON f.film_id = l.film_id " +
Можно сделать join к уже агрегированной таблице as select l.film_id, count(l.film_id) from likes l group by l.film_id и избавиться от группировки по всем полям

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbDao.java
> +    private void checkIfExistsByFields(Film film) throws EntityAlreadyExistsException {
throws EntityAlreadyExistsException лишний, потому что это непроверяемое исключение

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbDao.java
> +        if (findAll().stream().anyMatch(f ->
Получение всех фильмов из БД выглядит избыточным, лучше отфильтровать на уровне запроса в БД

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbDao.java
> +        if (findAll().stream().anyMatch(u ->
Проверку лучше сделать на уровне запроса в БД

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbDao.java
> +        return findAll()
Проверку лучше сделать на уровне запроса в БД

2023-05-11 21:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/guard/FilmGuard.java
>  public class FilmGuard extends Guard<Film> {
f.getId() == id должно сравниваться через equals(...)

2023-05-11 21:37 UTC, NikolaiDem reviewed
Сборку нужно починить)

2023-05-16 23:16 UTC, HoneyVanity commented
Не могу починить сборку, не проходит код стайл, уже несколько раз переделывала все пробелы и отступы
> 
![image](https://github.com/HoneyVanity/java-filmorate/assets/105306067/f2fc2786-234b-45cf-8fb9-1fdcca3a2157)

2023-05-17 19:32 UTC, HoneyVanity commented
> Сборку нужно починить)

исправила весь кодстайл, из-за которого валятся проверки, но не получается запушить, 
![image](https://github.com/HoneyVanity/java-filmorate/assets/105306067/912b1672-f051-4953-9bd8-9bc62d25ef5d)

2023-05-17 20:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbDao.java
> +                .genres((genreDao.getByFilmId(resultSet.getInt("film_id"))))
Не исправлено

2023-05-17 21:00 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/queries/FilmQueries.java
> +            "LEFT JOIN likes AS l ON f.film_id = l.film_id " +
Например, так
SELECT 
  f.film_id, --и остальные поля
  CASE WHEN l.cnt is NULL THEN 0 ELSE l.cnt END AS likes 
FROM 
  films AS f 
  INNER JOIN mpa AS m ON f.mpa_id = m.mpa_id 
  LEFT JOIN (
    select 
      l.film_id, 
      count(l.film_id) as cnt
    from 
      likes l 
    group by 
      l.film_id
  ) AS l ON f.film_id = l.film_id 
ORDER BY 
  likes DESC
LIMIT 
  10;

2023-05-17 21:17 UTC, NikolaiDem requested changes

2023-05-17 21:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/guard/FilmGuard.java
> +        if (filmStorage.findAll().stream().anyMatch(f -> f.getId().equals(id))) {
Проверку лучше сделать на уровне запроса в БД
Аналогично для остальных guards

2023-05-17 22:27 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbDao.java
> +                .genres((genreDao.getByFilmId(resultSet.getInt("film_id"))))
Не поняла, как это реализовать, потому что получив список фильмов без жанров и отдельно список всех жанров я не могу их сконнектить, так как нет связи по film_id

2023-05-17 23:30 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/guard/FilmGuard.java
> +        if (filmStorage.findAll().stream().anyMatch(f -> f.getId().equals(id))) {
Не совсем поняла, как реализовать такой вариант, потому что у меня запросы к базе данных в других бинах - DBDao, когда пытаюсь делать запросы через guards, приходится дублировать методы MapRowTo и тесты крашатся

2023-05-17 23:44 UTC, HoneyVanity commented on src/main/java/ru/yandex/practicum/filmorate/dao/queries/FilmQueries.java
> +            "LEFT JOIN likes AS l ON f.film_id = l.film_id " +
с запросом "SELECT f.film id, f.name, f.description, f.release_date, f.duration, f.mpa_id" +
"CASE WHEN l.cnt is NULL THEN 0 ELSE l.cnt END AS likes " +
"FROM films AS f " +
"INNER JOIN mpa AS m ON f.mpa_id = m.mpa_id" +
"LEFT JOIN(select l.film_id,count(l.film_id) AS cnt FROM likes AS l GROUP BY l.film_id)" +
"AS l ON f.film_id =l.film_id" +
"ORDER BY likes DESC LIMIT ?;";

у меня крашатся постман-тесты, фильмы не возвращаются из БД

2023-05-19 18:55 UTC, NikolaiDem approved these changes

2023-05-19 18:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbDao.java
> +                    genres.stream()
Перебора всей коллекции жанров лучше избегать, так как создается квадратичная сложность)

2023-05-20 12:48 UTC, merged